import 'package:latlong2/latlong.dart';
import 'models.dart';

// POI Centers
final LatLng overpoortCenter = const LatLng(51.0385, 3.7255);
final LatLng oudeMarktCenter = const LatLng(50.8784, 4.7001); // Leuven Oude Markt
final LatLng eilandjeCenter = const LatLng(51.2307, 4.4074); // Antwerpen Eilandje
final LatLng brusselCentrum = const LatLng(50.8466, 4.3528); // Brussel Centrum
final LatLng hasseltCentrum = const LatLng(50.9303, 5.3378); // Hasselt Centrum

final Map<String, LatLng> poiCenters = {
  'Overpoort': overpoortCenter,
  'Oude Markt, Leuven': oudeMarktCenter,
  'Eilandje, Antwerpen': eilandjeCenter,
  'Brussel Centrum': brusselCentrum,
  'Hasselt Centrum': hasseltCentrum,
};

final List<Place> mockPlaces = [
  // GENT - OVERPOORT
  // CLUBS
  Place(
    id: 'c1',
    name: 'De Salamander',
    address: 'Overpoortstraat 11, 9000 Gent',
    location: const LatLng(51.0387, 3.7252),
    type: LocationType.club,
    poi: 'Overpoort',
    genre: 'Party/Techno',
    status: ClubStatus.event,
    eventName: 'Kringfeest VTK',
    organizer: 'Vlaamse Technische Kring',
    promo: 'Gratis Vat om 23:00',
    tags: ['Kringen', 'Vat', 'Gratis Inkom', 'Chillzone'],
    facilities: ['Gratis Water', 'Lounge'],
    isVereniging: true,
    startTime: DateTime.now().subtract(const Duration(minutes: 30)),
    crowdLevel: 'Sfeervol',
    waitTime: 'Geen rij',
    lastVibeUpdate: DateTime.now().subtract(const Duration(minutes: 12)),
  ),
  Place(
    id: 'c2',
    name: 'Twitch',
    address: 'Overpoortstraat 9, 9000 Gent',
    location: const LatLng(51.0382, 3.7258),
    type: LocationType.club,
    poi: 'Overpoort',
    genre: 'R&B / Urban',
    status: ClubStatus.open,
    eventName: 'Urban Night by VGK',
    organizer: 'Vlaamse Geneeskundige Kring',
    isFlashPromoActive: true,
    promo: 'FLASH: 1+1 Gratis Shotjes',
    tags: ['Flash Promo', 'R&B'],
    isVereniging: true,
    startTime: DateTime.now().add(const Duration(hours: 1)),
    crowdLevel: 'Druk',
    waitTime: '10 min rij',
    lastVibeUpdate: DateTime.now().subtract(const Duration(minutes: 5)),
  ),
  Place(
    id: 'c3',
    name: 'Yucca',
    address: 'Overpoortstraat 15, 9000 Gent',
    location: const LatLng(51.0384, 3.7251),
    type: LocationType.club,
    poi: 'Overpoort',
    genre: 'Commercial',
    status: ClubStatus.open,
    eventName: 'Studentenavond',
    tags: ['Studenten', 'Commercial'],
    facilities: ['Buitenterras', 'Vestiaire'],
    crowdLevel: 'Rustig',
    waitTime: 'Geen rij',
    lastVibeUpdate: DateTime.now().subtract(const Duration(minutes: 25)),
  ),
  Place(
    id: 'c4',
    name: 'Canard Bizar',
    address: 'Overpoortstraat 4, 9000 Gent',
    location: const LatLng(51.0389, 3.7256),
    type: LocationType.club,
    poi: 'Overpoort',
    genre: 'All-round',
    status: ClubStatus.closed,
    tags: ['All-round', 'Cocktails'],
  ),

  // LEUVEN - OUDE MARKT
  Place(
    id: 'l1',
    name: 'Café Belge',
    address: 'Oude Markt 35, 3000 Leuven',
    location: const LatLng(50.8783, 4.7003),
    type: LocationType.club,
    poi: 'Oude Markt, Leuven',
    genre: 'Student/Party',
    status: ClubStatus.open,
    tags: ['Studenten', 'Pintjes'],
    facilities: ['Gratis Water', 'Zithoek'],
    crowdLevel: 'Sfeervol',
    waitTime: 'Geen rij',
    lastVibeUpdate: DateTime.now().subtract(const Duration(minutes: 8)),
  ),
  Place(
    id: 'l2',
    name: 'De Prof',
    address: 'Naamsestraat 34, 3000 Leuven',
    location: const LatLng(50.8778, 4.7011),
    type: LocationType.club,
    poi: 'Oude Markt, Leuven',
    genre: 'Dance',
    status: ClubStatus.event,
    eventName: 'Fakbar Night',
    tags: ['Kringen', 'Promotie'],
    crowdLevel: 'Druk',
    waitTime: '5 min',
    lastVibeUpdate: DateTime.now().subtract(const Duration(minutes: 2)),
  ),

  // ANTWERPEN - EILANDJE
  Place(
    id: 'a1',
    name: 'Lima',
    address: 'Rijnkaai 2, 2000 Antwerpen',
    location: const LatLng(51.2312, 4.4068),
    type: LocationType.club,
    poi: 'Eilandje, Antwerpen',
    genre: 'VIP / Urban',
    status: ClubStatus.open,
    tags: ['VIP', 'Cocktails'],
    facilities: ['Zithoek', 'Vestiaire'],
    crowdLevel: 'Rustig',
  ),
  Place(
    id: 'a2',
    name: 'Ampere',
    address: 'Simonsstraat 21, 2018 Antwerpen',
    location: const LatLng(51.2132, 4.4184),
    type: LocationType.club,
    poi: 'Antwerpen Centrum',
    genre: 'Techno',
    status: ClubStatus.event,
    eventName: 'KNTXT',
    tags: ['Techno', 'Underground'],
    facilities: ['Kluisjes', 'Gratis Water'],
    crowdLevel: 'Zeer Druk',
  ),

  // BRUSSEL
  Place(
    id: 'b1',
    name: 'Fuse',
    address: 'Blaesstraat 208, 1000 Brussel',
    location: const LatLng(50.8344, 4.3465),
    type: LocationType.club,
    poi: 'Brussel Centrum',
    genre: 'Techno',
    status: ClubStatus.open,
    tags: ['Legendary', 'Techno'],
    facilities: ['Kluisjes', 'Rookruimte'],
    crowdLevel: 'Druk',
    waitTime: '15 min',
  ),
  Place(
    id: 'b2',
    name: 'Zodiak',
    address: 'Kaasmarkt 10, 1000 Brussel',
    location: const LatLng(50.8465, 4.3541),
    type: LocationType.club,
    poi: 'Brussel Centrum',
    genre: 'Electronic',
    status: ClubStatus.open,
    tags: ['Electronic', 'House'],
    crowdLevel: 'Sfeervol',
  ),
  Place(
    id: 'b3',
    name: 'Spirito',
    address: 'Stassartstraat 18, 1050 Elsene',
    location: const LatLng(50.8358, 4.3601),
    type: LocationType.club,
    poi: 'Brussel Centrum',
    genre: 'VIP/House',
    status: ClubStatus.event,
    eventName: 'Exclusive Night',
    tags: ['VIP', 'Dresscode'],
    facilities: ['VIP Area', 'Zithoek'],
    crowdLevel: 'Druk',
  ),

  // HASSELT
  Place(
    id: 'h1',
    name: 'Versuz',
    address: 'Gouverneur Verwilghensingel 70, 3500 Hasselt',
    location: const LatLng(50.9329, 5.3533),
    type: LocationType.club,
    poi: 'Hasselt Centrum',
    genre: 'Dance/Commercial',
    status: ClubStatus.event,
    eventName: 'Saturnight',
    promo: 'Gratis inkom voor 00:00',
    tags: ['Mega Club', 'Dance'],
    facilities: ['Kluisjes', 'VIP Area', 'Buitenterras', 'Chillzone'],
    crowdLevel: 'Druk',
    waitTime: '10 min',
  ),

  // FOOD (NIGHT HACKS)
  Place(
    id: 'f1',
    name: 'De Gouden Saté (Julientje)',
    address: 'Overpoortstraat 51, 9000 Gent',
    location: const LatLng(51.0375, 3.7259),
    type: LocationType.food,
    tags: ['Frituur', 'Iconisch', 'Late Night Snack'],
    status: ClubStatus.open,
    crowdLevel: 'Lange rij',
    waitTime: '15 min',
    lastVibeUpdate: DateTime.now().subtract(const Duration(minutes: 2)),
  ),
  Place(
    id: 'f2',
    name: 'Nachtwinkel Overpoort',
    address: 'Overpoortstraat 22, 9000 Gent',
    location: const LatLng(51.0380, 3.7255),
    type: LocationType.food,
    tags: ['Nachtwinkel', 'Drank', 'Snacks'],
    status: ClubStatus.open,
    crowdLevel: 'Vlotte bediening',
  ),
];
